# pull image from linux: 
from openjdk:8-jdk-alpine
# copy fileBuild.jar to docker
copy target/admin-server-0.0.1-SNAPSHOT.jar admin-server-0.1.jar
# run java file
ENTRYPOINT ["java","-jar", "/admin-server-0.1.jar"]
